### ISSUE TITLE
saml_reader does not work with Python 3.11

### ISSUE THREAD

**Issue by cade-curry** [clegaspi/saml_reader#82]
When using Python 3.11, `saml_reader` errors out.  It looks like it may have something to do with regex validation and global inline flags not being parsed correctly.

On Python 3.10, the program works as expected.

> Traceback (most recent call last):
  File "/Sandbox/saml_env/bin/saml_reader", line 8, in <module>
    sys.exit(start_saml_reader())
             ^^^^^^^^^^^^^^^^^^^
  File "/Sandbox/saml_env/lib/python3.11/site-packages/saml_reader/cli.py", line 437, in start_saml_reader
    cli(sys.argv[1:])
  File "/Sandbox/saml_env/lib/python3.11/site-packages/saml_reader/cli.py", line 113, in cli
    run_analysis(
  File "/Sandbox/saml_env/lib/python3.11/site-packages/saml_reader/cli.py", line 215, in run_analysis
    validator.validate_configuration()
  File "/Sandbox/saml_env/lib/python3.11/site-packages/saml_reader/validation/mongo.py", line 56, in validate_configuration
    test_suite.run()
  File "/Sandbox/saml_env/lib/python3.11/site-packages/saml_reader/validation/graph_suite.py", line 294, in run
    self._run_suite()
  File "/Sandbox/saml_env/lib/python3.11/site-packages/saml_reader/validation/graph_suite.py", line 339, in _run_suite
    test.run(self._context)
  File "/Sandbox/saml_env/lib/python3.11/site-packages/saml_reader/validation/graph_suite.py", line 127, in run
    result = self._func({x: context[x] for x in self.required_context})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Sandbox/saml_env/lib/python3.11/site-packages/saml_reader/validation/mongo.py", line 709, in verify_name_id_pattern
    return MongoTestSuite._matches_regex(UserInputValidator().get_validation_regex('email'),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Sandbox/saml_env/lib/python3.11/site-packages/saml_reader/validation/mongo.py", line 444, in _matches_regex
    matcher = re.compile(regex)
              ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 2

**Comment by clegaspi** [comment]
This was fixed in #88
